### Write a function so that the columns of the output matrix are powers of the input vector.

### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

### HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [ ]:
import numpy as np

In [49]:
def vandermonde(ipv, n, increasing=False):
    
    if not increasing:
        matrix = np.array([x**(n-1-i) for x in ipv for i in range(n)]).reshape(ipv.size,n)
    elif increasing:
        matrix = np.array([x**i for x in ipv for i in range(n)]).reshape(ipv.size,n)
    
    return matrix

In [50]:
input_v = np.array([1,2,3,4,5])
matx_dec = vandermonde(inputvector,matx_col,False)
matx_inc = vandermonde(inputvector,matx_col,True)

In [51]:
print("The input array is:",input_v,"\n")
print("Vandermonde matrix of the input array in decreasing order of powers:\n",matx_dec,"\n")
print("Vandermonde matrix of the input array in increasing order of powers:\n",matx_inc,"\n")

The input array is: [1 2 3 4 5] 

Vandermonde matrix of the input array in decreasing order of powers:
 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

Vandermonde matrix of the input array in increasing order of powers:
 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]] 



In [52]:
input_v = np.array([1,2,4,6,8,10])

In [53]:
print("The input array is:",input_v,"\n")
print("Vandermonde matrix of the input array in decreasing order of powers:\n",matx_dec,"\n")
print("Vandermonde matrix of the input array in increasing order of powers:\n",matx_inc,"\n")

The input array is: [ 1  2  4  6  8 10] 

Vandermonde matrix of the input array in decreasing order of powers:
 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

Vandermonde matrix of the input array in increasing order of powers:
 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]] 



### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
### The moving average sequence has n-k+1 elements as shown below.
### The moving averages with k=4 of a ten-value sequence (n=10) is shown below
### i 1 2 3 4 5 6 7 8 9 10
### ===== == == == == == == == == == ==
### Input 10 20 30 40 50 60 70 80 90 100
### y1 25 = (10+20+30+40)/4
### y2 35 = (20+30+40+50)/4
### y3 45 = (30+40+50+60)/4
### y4 55 = (40+50+60+70)/4
### y5 65 = (50+60+70+80)/4
### y6 75 = (60+70+80+90)/4
### y7 85 = (70+80+90+100)/4
### Thus, the moving average sequence has n-k+1=10-4+1=7 values.

### Question: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [56]:
def moving_average(z, n=3) :
    num = np.cumsum(z, dtype=float)
    num[n:] = num[n:] - num[:-n]
    return num[n - 1:] / n
z = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_average(z, n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
